/**
 * Reads the Nano S Plus + Flex install bundles from `apps/` and emits a
 * base64-inlined TypeScript module at
 * `src/core/installer/bundled-artifacts.generated.ts`.
 *
 * The generated module is consumed by `bundled-artifacts.ts` so that
 * `@railgun-community/ledger-client` consumers (extensions, dapps) can ship the install
 * artifacts inside the JS bundle without webpack/vite asset plumbing.
 *
 * Re-runs are cheap and idempotent. Wired into `prebuild`.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const TARGETS = ['nanosp', 'flex'] as const;
type Target = typeof TARGETS[number];

// Bump this when shipping a new app build. Artifacts are read from
// `apps/{target}/{APP_VERSION}/{app.apdu,app.elf}`.
const APP_VERSION = '1.6.1';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const outFile = resolve(repoRoot, 'src/core/installer/bundled-artifacts.generated.ts');

function loadAsBase64(target: Target, file: 'app.apdu' | 'app.elf'): string {
  const path = resolve(repoRoot, 'apps', target, APP_VERSION, file);
  return readFileSync(path).toString('base64');
}

const lines: string[] = [
  '// AUTO-GENERATED by scripts/embed-artifacts.ts — DO NOT EDIT.',
  '// Re-run `yarn build` (or `tsx scripts/embed-artifacts.ts`) to refresh.',
  '',
  '/* eslint-disable */',
  '',
  'export const BUNDLED_ARTIFACTS_BASE64 = {',
];

for (const target of TARGETS) {
  const apdu = loadAsBase64(target, 'app.apdu');
  const elf = loadAsBase64(target, 'app.elf');
  lines.push(`  ${target}: {`);
  lines.push(`    apdu: '${apdu}',`);
  lines.push(`    elf: '${elf}',`);
  lines.push('  },');
}

lines.push('} as const;', '');

writeFileSync(outFile, lines.join('\n'));

const totalBytes = lines.reduce((n, l) => n + l.length, 0);
console.log(`[embed-artifacts] wrote ${outFile} (${(totalBytes / 1024).toFixed(1)} KB)`);